// MODULES //

// COMPONENTS //
import ContainerLayout from "@/components/ContainerLayout";

// SECTIONS //

// PLUGINS //
import { SessionProvider } from "next-auth/react";

// UTILS //
import SmoothScrolling from "@/utils/SmoothScrolling";
import { auth } from "@/auth";

// STYLES //
import "@/styles/globals/globals.scss";
import "./globals.tailwind.css";

// IMAGES //

// DATA //

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

/** Layout */
export default async function RootLayout({ children }) {
	const session = await auth();
	return (
		<html lang="en">
			<body>
				<SessionProvider session={session}>
					<ContainerLayout>{children}</ContainerLayout>
				</SessionProvider>
			</body>
		</html>
	);
}
