// MODULES //

// COMPONENTS //
import ContainerLayout from "@/components/ContainerLayout";

// SECTIONS //

// PLUGINS //

// UTILS //
import SmoothScrolling from "@/utils/SmoothScrolling";

// STYLES //
import "@/styles/globals/globals.scss";
import "./globals.tailwind.css";

// IMAGES //

// DATA //

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

/** Layout */
export default async function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<ContainerLayout>{children}</ContainerLayout>
			</body>
		</html>
	);
}
